name: markab
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  mask_text_input_formatter: ^2.7.0
  pinput: ^3.0.1
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  get_it: ^7.6.4
  bloc: ^8.1.2
  meta: ^1.10.0
  flutter_bloc: ^8.1.3
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  yandex_mapkit: ^3.4.0
  geolocator: ^10.1.0
  toggle_switch: ^2.1.0
  freezed: ^2.4.7
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: ProximaNova
      fonts:
         - asset: assets/fonts/Proxima Nova/proximanova_regular.ttf
         - asset: assets/fonts/Proxima Nova/proximanova_light.otf
           weight: 300
         - asset: assets/fonts/Proxima Nova/proximanova_extrabold.otf
           weight: 800
         - asset: assets/fonts/Proxima Nova/proximanova_bold.otf
           weight: 700